services:
  - type: web
    name: dashboard-service
    env: python
    rootDir: dashboard-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false

  - type: worker
    name: bot-service
    env: python
    rootDir: bot-service
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DISCORD_TOKEN
        sync: false
      - key: BOT_PREFIX
        value: "a "
      - key: OWNER_ID
        sync: false
